### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by panagiotispir** [analogdevicesinc/libad9361-iio#123]
I have trouble to install this package
when I perform
`make` after
` cmake -DLIBIIO_INCLUDEDIR=/usr/include/iio -DLIBIIO_LIBDIR=/usr/lib/x86_64-linux-gnu`

I get
`panos@panos-SER ~/libad9361-iio (main) [2]> make
[  4%] Building C object CMakeFiles/ad9361.dir/ad9361_fmcomms5_phase_sync.c.o
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c: In function ‘dds_tx_phase_rotation’:
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:121:13: warning: implicit declaration of function ‘iio_channel_attr_write_longlong’; did you mean ‘iio_attr_write_longlong’? [-Wimplicit-function-declaration]
  121 |             iio_channel_attr_write_longlong(dds_out[d][j], "phase", i);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             iio_attr_write_longlong
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c: In function ‘configure_ports’:
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:221:5: warning: implicit declaration of function ‘iio_device_debug_attr_write_longlong’ [-Wimplicit-function-declaration]
  221 |     iio_device_debug_attr_write_longlong(dev_phy, "calibration_switch_control",
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:225:5: warning: implicit declaration of function ‘iio_channel_attr_write’; did you mean ‘iio_channel_write’? [-Wimplicit-function-declaration]
  225 |     iio_channel_attr_write(iio_device_find_channel(dev_phy, "voltage0", false),
      |     ^~~~~~~~~~~~~~~~~~~~~~
      |     iio_channel_write
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c: In function ‘trx_phase_rotation’:
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:272:19: warning: implicit declaration of function ‘iio_channel_attr_write_double’; did you mean ‘iio_attr_write_double’? [-Wimplicit-function-declaration]
  272 |             ret = iio_channel_attr_write_double(out0, "calibscale", (double)vcos);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   iio_attr_write_double
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c: In function ‘streaming_interfaces’:
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:295:9: error: too few arguments to function ‘iio_channel_enable’
  295 |         iio_channel_enable(rxa_chan_real);
      |         ^~~~~~~~~~~~~~~~~~
In file included from /home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:18:
/usr/include/iio/iio.h:925:12: note: declared here
  925 | __api void iio_channel_enable(const struct iio_channel *chn,
      |            ^~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:296:9: error: too few arguments to function ‘iio_channel_enable’
  296 |         iio_channel_enable(rxa_chan_imag);
      |         ^~~~~~~~~~~~~~~~~~
In file included from /home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:18:
/usr/include/iio/iio.h:925:12: note: declared here
  925 | __api void iio_channel_enable(const struct iio_channel *chn,
      |            ^~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:297:9: error: too few arguments to function ‘iio_channel_enable’
  297 |         iio_channel_enable(rxb_chan_real);
      |         ^~~~~~~~~~~~~~~~~~
In file included from /home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:18:
/usr/include/iio/iio.h:925:12: note: declared here
  925 | __api void iio_channel_enable(const struct iio_channel *chn,
      |            ^~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:298:9: error: too few arguments to function ‘iio_channel_enable’
  298 |         iio_channel_enable(rxb_chan_imag);
      |         ^~~~~~~~~~~~~~~~~~
In file included from /home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:18:
/usr/include/iio/iio.h:925:12: note: declared here
  925 | __api void iio_channel_enable(const struct iio_channel *chn,
      |            ^~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:307:13: error: too few arguments to function ‘iio_channel_disable’
  307 |             iio_channel_disable(rxa_chan_real);
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:18:
/usr/include/iio/iio.h:932:12: note: declared here
  932 | __api void iio_channel_disable(const struct iio_channel *chn,
      |            ^~~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:310:13: error: too few arguments to function ‘iio_channel_disable’
  310 |             iio_channel_disable(rxa_chan_imag);
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:18:
/usr/include/iio/iio.h:932:12: note: declared here
  932 | __api void iio_channel_disable(const struct iio_channel *chn,
      |            ^~~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:313:13: error: too few arguments to function ‘iio_channel_disable’
  313 |             iio_channel_disable(rxb_chan_real);
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:18:
/usr/include/iio/iio.h:932:12: note: declared here
  932 | __api void iio_channel_disable(const struct iio_channel *chn,
      |            ^~~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:316:13: error: too few arguments to function ‘iio_channel_disable’
  316 |             iio_channel_disable(rxb_chan_imag);
      |             ^~~~~~~~~~~~~~~~~~~
In file included from /home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:18:
/usr/include/iio/iio.h:932:12: note: declared here
  932 | __api void iio_channel_disable(const struct iio_channel *chn,
      |            ^~~~~~~~~~~~~~~~~~~
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c: In function ‘read_buffer_data’:
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:328:36: warning: implicit declaration of function ‘iio_buffer_end’; did you mean ‘iio_buffer_enable’? [-Wimplicit-function-declaration]
  328 |     uintptr_t buf_end = (uintptr_t)iio_buffer_end(buf);
      |                                    ^~~~~~~~~~~~~~
      |                                    iio_buffer_enable
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:329:26: warning: implicit declaration of function ‘iio_buffer_step’; did you mean ‘iio_buffer_cancel’? [-Wimplicit-function-declaration]
  329 |     ptrdiff_t buf_step = iio_buffer_step(buf);
      |                          ^~~~~~~~~~~~~~~
      |                          iio_buffer_cancel
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:331:31: warning: implicit declaration of function ‘iio_buffer_first’; did you mean ‘iio_block_first’? [-Wimplicit-function-declaration]
  331 |     for (src_ptr = (uintptr_t)iio_buffer_first(buf, chn);
      |                               ^~~~~~~~~~~~~~~~
      |                               iio_block_first
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c: In function ‘estimate_phase_diff’:
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:339:25: warning: implicit declaration of function ‘iio_buffer_refill’; did you mean ‘iio_buffer_enable’? [-Wimplicit-function-declaration]
  339 |     ssize_t nbytes_rx = iio_buffer_refill(rxbuf);
      |                         ^~~~~~~~~~~~~~~~~
      |                         iio_buffer_enable
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c: In function ‘ad9361_fmcomms5_phase_sync’:
/home/panos/libad9361-iio/ad9361_fmcomms5_phase_sync.c:591:11: warning: implicit declaration of function ‘iio_channel_attr_read_longlong’; did you mean ‘iio_attr_read_longlong’? [-Wimplicit-function-declaration]
  591 |     ret = iio_channel_attr_read_longlong(chan, "sampling_frequency", &sample_rate);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |           iio_attr_read_longlong
make[2]: *** [CMakeFiles/ad9361.dir/build.make:115: CMakeFiles/ad9361.dir/ad9361_fmcomms5_phase_sync.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:153: CMakeFiles/ad9361.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
`
I cannot understand which is the problem. Plz help.

**Comment by tfcollins** [comment]
Please verify you are using the correct version of libiio as documented in the Readme
