### ISSUE TITLE
Release a version

### ISSUE THREAD

**Issue by bogdanr** [analogdevicesinc/libad9361-iio#2]
It would be nice if you could tag and release a version like it was done for libiio.
Build scripts in many Linux distro work better if they can point to a specific version.

**Comment by tfcollins** [comment]
Tagged builds create releases automatically now: https://github.com/analogdevicesinc/libad9361-iio/commit/ac1d3a26386720405301b62343bd9341f81ae515

**Comment by rgetz** [comment]
There doesn't seem to be a build for Mac in the release section yet? It's in the build matrix, but doesn't deploy?
