### ISSUE TITLE
Create helper for filter designer to support sample rate only inputs

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libad9361-iio#3]
See function https://github.com/analogdevicesinc/ad936x-filter-wizard/blob/master/cook_input.m for reference.

**Comment by rgetz** [comment]
Do you want to have 2 functions? 
 - one that says "design a filter for the current settings, whatever they may be" (and RF bandwidth, and sample rates are defined by the current settings of the device? - use iio_read to get the settings?) 
- one which takes a sample rate as the input?

Both would need a context/device and write the FIR directly.

-Robin

**Comment by tfcollins** [comment]
Feature added here: https://github.com/analogdevicesinc/libad9361-iio/commit/edd0c42f3831237f98829ded0d058c46d1832a03
