### ISSUE TITLE
Enhance baseband_rate_function to accept RFBW

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libad9361-iio#5]
Ideally, user should supply RF bandwidth when generating filters but this would break current baseband_auto_rate.c function.

**Comment by rgetz** [comment]
Can't we read the RF bandwidth from the part?

**Comment by tfcollins** [comment]
So we could do that but you would require that its set to what you want before the bb_auto_rate is called.  That might be ok for OSC but as a default behavior outside of OSC it seems fragile.  I kinda don't like using the part's state as an info passing method.

**Comment by rgetz** [comment]
Yeah, it's easy to do that from the application, so doing it in the library might not be necessary.

I was just thinking that every time data rate or the RF bandwidth was changed, the app would just call - "load whatever filters is needed to fix things" function. :)

**Comment by tfcollins** [comment]
This functionality to specify RFBW is available in the merged filter generation API: https://github.com/analogdevicesinc/libad9361-iio/commit/edd0c42f3831237f98829ded0d058c46d1832a03
