### ISSUE TITLE
LIBIIO_INCLUDEDIR error installing from source.

### ISSUE THREAD

**Issue by GlenLangston** [analogdevicesinc/libad9361-iio#51]
Trying to install the latest adi code for pluto SDR on a raspberry pi 4,
but am having some configuration problems.

First tried packages, but the linux versions seem to have ADM devices built into the assumptions.
So tried from source, but get an error at the CMAKE step, 
pi@raspberrypi:~/libad9361-iio-0.2/build $  cmake -DCMAKE_INSTALL_PREFIX=/usr ../
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /usr/bin/git (found version "2.20.1") 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Using default dependencies for packaging
-- Package dependencies: libc6-dev (>= 2.19)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBIIO_INCLUDEDIR
   used as include directory in directory /home/pi/libad9361-iio-0.2
   used as include directory in directory /home/pi/libad9361-iio-0.2
   used as include directory in directory /home/pi/libad9361-iio-0.2

My configuration is as follows:
pi@raspberrypi:~/libad9361-iio-0.2/build $ uname -a
Linux raspberrypi 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux

Googling has not yielded me any hints yet.

Suggestions?

Thanks
Glen

**Comment by tfcollins** [comment]
How did you install libiio?

**Comment by GlenLangston** [comment]
Hi Travis,

Thanks for your very quick response.

I’ve been exploring some issues of the install.

Part of the problem seems to be some versioning of python.  Do you happen to know if
the ADI code is compatible with python2.7 or only python3?

I found that an apt-get install of libiio-utils is not compatible with the latest version of
 
https://github.com/analogdevicesinc/libiio/releases/tag/v0.18

I did finally get versions to install with

pi@raspberrypi:~/Downloads $ sudo dpkg -i
./libiio-0.18.g4e22517-raspbian-9-armhf.deb
dpkg: warning: downgrading libiio from 0.18.ga3a4c08 to 0.18.g4e22517
(Reading database ... 151521 files and directories currently installed.)
Preparing to unpack .../libiio-0.18.g4e22517-raspbian-9-armhf.deb ...
Unpacking libiio (0.18.g4e22517) over (0.18.ga3a4c08) ...
Setting up libiio (0.18.g4e22517) ...
pi@raspberrypi:~/Downloads $ sudo ldconfig

However, I’m still not getting data rates higher than 3.2 MHz bandwidth (I+Q).

Also I run gnu radio-companion, I’m not getting the underflow or overflow
flags.

In a separate topic related to your presentation

I think this: 

pip install pyadi-iio

To get this to work I need to export the python path
export PYTHONPATH=.local/lib/python2.7:/usr/local/lib/python2.7:/usr/lib/python2.7is not compatible with python2.7

as I get an error on import

pi@raspberrypi:~ $ python
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import adi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/adi/__init__.py", line 34, in <module>
    from adi.ad9361 import *
  File "/home/pi/.local/lib/python2.7/site-packages/adi/ad9361.py", line 35, in <module>
    from adi.rx_tx import rx_tx
  File "/home/pi/.local/lib/python2.7/site-packages/adi/rx_tx.py", line 44
    _ctrl: iio.Device = []
         ^
SyntaxError: invalid syntax

Thanks for your help.   I’ll keep exploring.

Glen

**Comment by GlenLangston** [comment]
Hi Travis,

Thanks again for your video describing the PlutoSDR source improvements.

I’ve attempted to install the latest gr-iio code,
(with git clone per the instructions)
but continue to find the PlutoSDR Source block does not have the “filter” tab,
indicating I’m missing something about where to get the source.

What web site would you use to get the latest PlutoSDR source block?
I am using the 3.7.13.4 version of gnu radio.  Do I need to use 3.8?

Thanks

Glen
I’m trying to keep this on a Raspberry Pi 4.  Will that work or do I
need an Intel computer?

**Comment by tfcollins** [comment]
So let me address issues related to libad9361-iio here, if you have questions about other software components please ask them in our support forum for Pluto here: https://ez.analog.com/adieducation/university-program , GitHub is more for bugs, but I am happy to help on EngineerZone.

> Part of the problem seems to be some versioning of python.  Do you happen to know if
the ADI code is compatible with python2.7 or only python3?
>
>I found that an apt-get install of libiio-utils is not compatible with the latest version of

Mixing and matching apt and source(or a different package source) is generally not a good idea. When you install libiio from github it will include the libiio-utils. I generally don't use apt for libiio since the packages are usually ancient.

**Comment by GlenLangston** [comment]
Hi Travis,

Thanks for your suggestion; I will try to avoid apt.

I’m to understand that I should prefer git clone then build?

Best regards

Glen

**Comment by tfcollins** [comment]
Yes, or just use the packages from one source.

-Travis

**Comment by GlenLangston** [comment]
Hi Travis,

I've repeatedly installed libiio and libad9361-iio , etc through gr-iio

but I never seem to get any speed up in data transfer.   The maximum data
rate that I can get without
dropping samples is 3.2 MHz.

I'm installing from source, via git clone etc.

One question, which library upgrade is the most likely to improve the pluto
SDR data transfer rate
Ie libad9361-iio ?

I'm doing all this within gnuradio 3.7.13.4  as I've still not gotten all
of 3.8 working on a raspberry pi.

Thanks
Glen

**Comment by tfcollins** [comment]
Glen,

Please direct those questions here: https://ez.analog.com/adieducation/university-program
libad9361 is really unrelated.

-Travis

**Comment by tfcollins** [comment]
I think the libad9361 specific aspects are answered here. Closing for now. Reopen if this is still an issue.
