### ISSUE TITLE
Segmentation fault on any radio program

### ISSUE THREAD

**Issue by Ev1lbl0w** [analogdevicesinc/libad9361-iio#56]
I'm using an ADALM-PLUTO device, and have installed this driver to use with programs such as **SigDigger**. However, I get a segmentation fault in those programs.

Looking at the core dump and by compilling some libraries, I found out that the code responsible for finding devices *(in [SoapyPlutoSDR](https://github.com/pothosware/SoapyPlutoSDR/blob/472e9a09b80e15148383efda3702773548c7962c/PlutoSDR_Settings.cpp#L35))* is returning null values:

```
dev = iio_context_find_device(ctx, "ad9361-phy");
rx_dev = iio_context_find_device(ctx, "cf-ad9361-lpc");
tx_dev = iio_context_find_device(ctx, "cf-ad9361-dds-core-lpc");
this->setAntenna(SOAPY_SDR_RX, 0, "A_BALANCED");
this->setAntenna(SOAPY_SDR_TX, 0, "A");
```

Both `dev`, `rx_dev` and `tx_dev` are initialized to 0x00, causing the crash.

I'm using Arch Linux, and installed [soapyplutosdr](https://www.archlinux.org/packages/community/x86_64/soapyplutosdr/) which should include everything needed AFAIK.

**Comment by tfcollins** [comment]
None of these calls are related to libad9361. I would suggest contacting Josh the maintainer of soapyplutosdr.

-Travis

**Comment by Ev1lbl0w** [comment]
Alright, I assumed by the string's content it was some sort of driver failure. I'll post on SoapyPlutoSDR then.
