### ISSUE TITLE
libad9361-iio will not build on Ubuntu 20.04

### ISSUE THREAD

**Issue by 76nic** [analogdevicesinc/libad9361-iio#65]
Dear AD,
libad9361-iio will not build on Ubuntu 20.04. I followed the following instructions:

> git clone https://github.com/analogdevicesinc/libad9361-iio.git
> cd libad9361-iio
> cmake ./
> make
> sudo make install

But I get the following error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBIIO_INCLUDEDIR
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/test
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
   used as include directory in directory /home/ku/libini/build/libad9361-iio/bindings/matlab
LIBIIO_LIBRARIES
    linked by target "ad9361" in directory /home/ku/libini/build/libad9361-iio
    linked by target "FilterDesignerTest" in directory /home/ku/libini/build/libad9361-iio/test
    linked by target "GenerateRatesTest" in directory /home/ku/libini/build/libad9361-iio/test
    linked by target "FilterDesignerHardwareTest" in directory /home/ku/libini/build/libad9361-iio/test
    linked by target "AutoRateTest" in directory /home/ku/libini/build/libad9361-iio/test
    linked by target "FMComms5SyncTest" in directory /home/ku/libini/build/libad9361-iio/test

-- Configuring incomplete, errors occurred!

Could you please help me to fix that?

Many thanks!
Best regards,
76nic
[CMakeOutput.log](https://github.com/analogdevicesinc/libad9361-iio/files/5900524/CMakeOutput.log)

**Comment by mhennerich** [comment]
Did you build and install libiio?

**Comment by 76nic** [comment]
Many thanks Michael for your help. After installing libiio following that instructions "https://wiki.analog.com/resources/tools-software/linux-software/libiio#how_to_build_it" I was able to build the libad9361-iio just fine.
The instruction to install libiio (link above) state that libiio will be installed in /usr. However, in my case I only can find it installed in /usr/lib/x86_64-linux-gnu/.
Building the IIO-Oscilloscope according to "https://wiki.analog.com/resources/tools-software/linux-software/iio_oscilloscope" works fine, but the application will not start up most likely due to missing link to libiio.
Again many thanks!
Best regards,
76nic
