### ISSUE TITLE
Using libad9361-iio for matlab

### ISSUE THREAD

**Issue by ilhamdestyo** [analogdevicesinc/libad9361-iio#66]
how i can use the libad9361-iio after install libad9361-setup?

**Comment by tfcollins** [comment]
libad9361 will come with Transceiver Toolbox and is leveraged for sample rate configurations: https://github.com/analogdevicesinc/TransceiverToolbox/blob/master/+adi/+AD9361/Rx.m#L240

**Comment by tfcollins** [comment]
Closing since no comment in 2 weeks. Feel free to reopen.
