### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by nunojpg** [analogdevicesinc/libad9361-iio#97]
https://analogdevicesinc.github.io/libad9361-iio/

This returns Page not found: "you must provide an index.html file."

**Comment by tfcollins** [comment]
@nunojpg thanks for reporting.  Looks like this happened when the last tag got created with the switch to a different CI.

@ccraluca can you look into this issue? Probably just reverting the commit in gh-pages will be enough for now as the library itself has not changed from an API level

**Comment by SRaus** [comment]
Issue got fixed.
